// /app/redux/actions/actionTypes.js

// utility
export const LOADING="LOADING";

// divisions
export const GET_ALL_DIVISIONS="GET_ALL_DIVISIONS";
export const GET_ALL_DIVISIONS_SUCCESS="GET_ALL_DIVISIONS_SUCCESS";
export const GET_ALL_DIVISIONS_ERROR="GET_ALL_DIVISIONS_ERROR";
export const GET_DIVISION="GET_DIVISION";
export const GET_DIVISION_SUCCESS="GET_DIVISION_SUCCESS";
export const GET_DIVISION_ERROR="GET_DIVISION_ERROR";
export const ADD_DIVISION="ADD_DIVISION";
export const ADD_DIVISION_SUCCESS="ADD_DIVISION_SUCCESS";
export const ADD_DIVISION_ERROR="ADD_DIVISION_ERROR";
export const EDIT_DIVISION="EDIT_DIVISION";
export const EDIT_DIVISION_SUCCESS="EDIT_DIVISION_SUCCESS";
export const EDIT_DIVISION_ERROR="EDIT_DIVISION_ERROR";
export const DELETE_DIVISION="DELETE_DIVISION";
export const DELETE_DIVISION_SUCCESS="DELETE_DIVISION_SUCCESS";
export const DELETE_DIVISION_ERROR="DELETE_DIVISION_ERROR";
export const SET_CURRENT_DIVISION_ID="SET_CURRENT_DIVISION_ID";

// staff
export const GET_ALL_STAFF="GET_ALL_STAFF";
export const GET_ALL_STAFF_SUCCESS="GET_ALL_STAFF_SUCCESS";
export const GET_ALL_STAFF_ERROR="GET_ALL_STAFF_ERROR";
export const GET_STAFF_MEMEBER="GET_STAFF_MEMBER";
export const GET_STAFF_MEMBER_SUCCESS="GET_STAFF_MEMBER_SUCCESS";
export const GET_STAFF_MEMBER_ERROR="GET_STAFF_MEMBER_ERROR";
export const ADD_STAFF_MEMBER="ADD_STAFF_MEMBER";
export const ADD_STAFF_MEMBER_SUCCESS="ADD_STAFF_MEMBER_SUCCESS";
export const ADD_STAFF_MEMBER_ERROR="ADD_STAFF_MEMBER_ERROR";
export const EDIT_STAFF_MEMBER="EDIT_STAFF_MEMBER";
export const EDIT_STAFF_MEMBER_SUCCESS="EDIT_STAFF_MEMBER_SUCCESS";
export const EDIT_STAFF_MEMBER_ERROR="EDIT_STAFF_MEMBER_ERROR";
export const DELETE_STAFF_MEMBER="DELETE_STAFF_MEMBER";
export const DELETE_STAFF_MEMBER_SUCCESS="DELETE_STAFF_MEMBER_SUCCESS";
export const DELETE_STAFF_MEMBER_ERROR="DELETE_STAFF_MEMBER_ERROR";

// teams
export const GET_ALL_TEAMS="GET_ALL_TEAMS";
export const GET_ALL_TEAMS_SUCCESS="GET_ALL_TEAMS_SUCCESS";
export const GET_ALL_TEAMS_ERROR="GET_ALL_TEAMS_ERROR";
export const GET_TEAM="GET_TEAM";
export const GET_TEAM_SUCCESS="GET_TEAM_SUCCESS";
export const GET_TEAM_ERROR="GET_TEAM_ERROR";
export const ADD_TEAM="ADD_TEAM";
export const ADD_TEAM_SUCCESS="ADD_TEAM_SUCESS";
export const ADD_TEAM_ERROR="ADD_TEAM_ERROR";
export const EDIT_TEAM="EDIT_TEAM";
export const EDIT_TEAM_SUCCESS="EDIT_TEAM_SUCCESS";
export const EDIT_TEAM_ERROR="EDIT_TEAM_ERROR";
export const DELETE_TEAM="DELETE_TEAM";
export const DELETE_TEAM_SUCCESS="DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_ERROR="DELETE_TEAM_ERROR";

// misc
export const GET_COACHES="GET_COACHES";
export const GET_COACHES_SUCCESS="GET_COACHES_SUCCESS";
export const GET_COACHES_ERROR="GET_COACHES_ERROR";
export const GET_COMMISIONERS="GET_COMMISIONERS";
export const GET_COMMISIONERS_SUCCESS="GET_COMMISIONERS_SUCCESS";
export const GET_COMMISIONERS_ERROR="GET_COMMISIONERS_ERROR";