// /app/redux/actions/actionTypes.js

export const LOADING="LOADING";

export const GET_ALL_DIVISIONS="GET_ALL_DIVISIONS";
export const GET_ALL_DIVISIONS_SUCCESS="GET_ALL_DIVISIONS_SUCCESS";
export const GET_ALL_DIVISIONS_ERROR="GET_ALL_DIVISIONS_ERROR";
export const GET_DIVISION="GET_DIVISION";
export const GET_DIVISION_SUCCESS="GET_DIVISION_SUCCESS";
export const GET_DIVISION_ERROR="GET_DIVISION_ERROR";
export const ADD_DIVISION="ADD_DIVISION";
export const ADD_DIVISION_SUCCESS="ADD_DIVISION_SUCCESS";
export const ADD_DIVISION_ERROR="ADD_DIVISION_ERROR";
export const EDIT_DIVISION="EDIT_DIVISION";
export const EDIT_DIVISION_SUCCESS="EDIT_DIVISION_SUCCESS";
export const EDIT_DIVISION_ERROR="EDIT_DIVISION_ERROR";
export const DELETE_DIVISION="DELETE_DIVISION";
export const DELETE_DIVISION_SUCCESS="DELETE_DIVISION_SUCCESS";
export const DELETE_DIVISION_ERROR="DELETE_DIVISION_ERROR";

export const GET_ALL_STAFF="GET_ALL_STAFF";
export const GET_ALL_STAFF_SUCCESS="GET_ALL_STAFF_SUCCESS";
export const GET_ALL_STAFF_ERROR="GET_ALL_STAFF_ERROR";
export const GET_STAFF_MEMEBER="GET_STAFF_MEMBER";
export const GET_STAFF_MEMBER_SUCCESS="GET_STAFF_MEMBER_SUCCESS";
export const GET_STAFF_MEMBER_ERROR="GET_STAFF_MEMBER_ERROR";
export const ADD_STAFF_MEMBER="ADD_STAFF_MEMBER";
export const ADD_STAFF_MEMBER_SUCCESS="ADD_STAFF_MEMBER_SUCCESS";
export const ADD_STAFF_MEMBER_ERROR="ADD_STAFF_MEMBER_ERROR";
export const EDIT_STAFF_MEMBER="EDIT_STAFF_MEMBER";
export const EDIT_STAFF_MEMBER_SUCCESS="EDIT_STAFF_MEMBER_SUCCESS";
export const EDIT_STAFF_MEMBER_ERROR="EDIT_STAFF_MEMBER_ERROR";
export const DELETE_STAFF_MEMBER="DELETE_STAFF_MEMBER";
export const DELETE_STAFF_MEMBER_SUCCESS="DELETE_STAFF_MEMBER_SUCCESS";
export const DELETE_STAFF_MEMBER_ERROR="DELETE_STAFF_MEMBER_ERROR";
